import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./ui/navbar";



export const metadata: Metadata = {
  title: "Portafolio BMC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-cover lg:h-screenbg-center bg-no-repeat bg-[url('/sky.jpg')] `} >
        
        {children}
    
      </body>
    </html>
  );
}
